version: "3"
services:
 wikijs:
   image: ghcr.io/requarks/wiki:2
   ports:
     - "3000:3000"
   environment:
     - DB_TYPE=sqlite
     - DB_FILEPATH=/wiki/data/wiki.db
   volumes:
     - ./data:/wiki/data
